services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: security_scanner_backend
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=8000
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: security_scanner_frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    networks:
      - app_network

# Define volumes for persistent data (e.g., ZAP data, nuclei templates)
volumes:
  zap_data:
  nuclei_templates:

# Define a network for services to communicate with each other
networks:
  app_network:
    driver: bridge