services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/app/backend
    environment:
      - DEBUG=true
      - HOST=0.0.0.0
      - PORT=9000
      - BACKEND_PORT=9000
    command: uvicorn backend.main:app --host 0.0.0.0 --port 9000
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
      - PORT=3004
      - VITE_API_URL=http://backend:9000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network

volumes:
  zap_data:
  nuclei_templates:

networks:
  app-network:
    driver: bridge
