# docker-compose.yml

services:
  backend:
    build:
      context: ./scanner-backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build:
      context: ./scanner-backend
      dockerfile: Dockerfile
    command: celery -A app.worker.celery worker --loglevel=info
    volumes:
      - ./scanner-backend:/app
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./scanner-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ptaas

  redis:
    image: redis:7
