services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    environment:
      - DEBUG=true
      - HOST=0.0.0.0
      - PORT=8000
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network

# Define volumes for persistent data
volumes:
  zap_data:
  nuclei_templates:

# Define a network for services to communicate with each other
networks:
  app-network:
    driver: bridge